name 'learn_chef_apache2'
maintainer 'Learn Chef'
maintainer_email 'learnchef@chef.io'
license 'Apache 2.0'
description 'Installs and configures package apache2 and sets a basic home page.'
long_description 'Installs and configures package apache2 and sets a basic home page. This cookbook is used by the Learn Chef tutorials. https://learn.chef.io'
supports 'ubuntu'
version '0.3.0'
